apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-site
  labels:
    app: my-site
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-site
  template:
    metadata:
      labels:
        app: my-site
    spec:
      containers:
        - name: my-site
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SITE_ENV
              value: {{ .Values.env.siteEnv | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
