# Шаг 1: Берем официальный готовый образ Nginx
FROM nginx:alpine

# Шаг 2: Копируем наш файл index.html внутрь контейнера в папку, где Nginx ищет сайты
COPY index.html /usr/share/nginx/html/index.html
